// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiemensCommunicator.EntityFramework.Core.DbContexts;

#nullable disable

namespace SiemensCommunicator.EntityFramework.Core.Migrations
{
    [DbContext(typeof(SiemensCommunicatorDbContext))]
    partial class SiemensCommunicatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SiemensCommunicator.Core.Models.PlcConnection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id")
                        .HasComment("主键ID");

                    b.Property<int>("CacheRefreshInterval")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CacheRefreshInterval")
                        .HasComment("缓存刷新间隔（毫秒）");

                    b.Property<int>("CpuType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CpuType")
                        .HasComment("PLC CPU类型");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt")
                        .HasComment("创建时间");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Ip")
                        .HasComment("PLC IP地址");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsActive")
                        .HasComment("是否激活");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name")
                        .HasComment("连接名称");

                    b.Property<int>("Rack")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Rack")
                        .HasComment("机架号");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Slot")
                        .HasComment("插槽号");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PlcConnections", t =>
                        {
                            t.HasComment("PLC连接配置表");
                        });
                });

            modelBuilder.Entity("SiemensCommunicator.Core.Models.PlcDataPoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id")
                        .HasComment("主键ID");

                    b.Property<int>("BitOffset")
                        .HasColumnType("INTEGER")
                        .HasColumnName("BitOffset")
                        .HasComment("位偏移");

                    b.Property<long>("ConnectionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ConnectionId")
                        .HasComment("关联的连接ID");

                    b.Property<string>("ConversionFormula")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("ConversionFormula")
                        .HasComment("转换公式");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt")
                        .HasComment("创建时间");

                    b.Property<int>("DataCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DataCount")
                        .HasComment("数据数量");

                    b.Property<int>("DataType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DataType")
                        .HasComment("数据类型");

                    b.Property<int>("DbNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DbNumber")
                        .HasComment("数据块编号");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description")
                        .HasComment("数据点描述");

                    b.Property<bool>("EnableCache")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EnableCache")
                        .HasComment("是否启用缓存");

                    b.Property<long?>("GroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("GroupId")
                        .HasComment("分组ID");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("MaxValue")
                        .HasComment("最大值");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("MinValue")
                        .HasComment("最小值");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name")
                        .HasComment("数据点名称");

                    b.Property<int>("StartByte")
                        .HasColumnType("INTEGER")
                        .HasColumnName("StartByte")
                        .HasComment("起始字节");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT")
                        .HasColumnName("Tags")
                        .HasComment("标签集合（JSON格式）");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("Unit")
                        .HasComment("单位");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UpdatedAt")
                        .HasComment("更新时间");

                    b.Property<string>("VarType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("VarType")
                        .HasComment("变量类型");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("GroupId");

                    b.HasIndex("Name");

                    b.ToTable("PlcDataPoints", t =>
                        {
                            t.HasComment("PLC数据点配置表");
                        });
                });

            modelBuilder.Entity("SiemensCommunicator.Core.Models.PlcGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id")
                        .HasComment("主键ID");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description")
                        .HasComment("分组描述");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name")
                        .HasComment("分组名称");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SortOrder")
                        .HasComment("排序顺序");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("PlcGroups", t =>
                        {
                            t.HasComment("PLC分组表");
                        });
                });

            modelBuilder.Entity("SiemensCommunicator.Core.Models.PlcTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id")
                        .HasComment("主键ID");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT")
                        .HasColumnName("Color")
                        .HasComment("标签颜色");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name")
                        .HasComment("标签名称");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PlcTags", t =>
                        {
                            t.HasComment("PLC标签表");
                        });
                });

            modelBuilder.Entity("SiemensCommunicator.Core.Models.PlcDataPoint", b =>
                {
                    b.HasOne("SiemensCommunicator.Core.Models.PlcConnection", "Connection")
                        .WithMany("DataPoints")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiemensCommunicator.Core.Models.PlcGroup", "Group")
                        .WithMany("DataPoints")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Connection");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SiemensCommunicator.Core.Models.PlcConnection", b =>
                {
                    b.Navigation("DataPoints");
                });

            modelBuilder.Entity("SiemensCommunicator.Core.Models.PlcGroup", b =>
                {
                    b.Navigation("DataPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
